SET NAMES UTF8;
DROP DATABASE IF EXISTS tedu;
CREATE DATABASE tedu CHARSET=UTF8;
USE tedu;
CREATE TABLE dept(
  did INT PRIMARY KEY,
  dname VARCHAR(5) NOT NULL,
  location VARCHAR(3) NOT NULL DEFAULT '北京',
  empCount SMALLINT NOT NULL DEFAULT 0
);
INSERT INTO dept VALUE(1,'研发部',default,666);
INSERT INTO dept VALUE(2,'财务部','广州',default);
CREATE TABLE emp(
  eid INT PRIMARY KEY,
  ename VARCHAR(6) NOT NULL,
  idCardNum VARCHAR(20) NOT NULL UNIQUE,
  salary INT DEFAULT NULL,
  deptId INT(5),
  FOREIGN KEY(deptId) REFERENCES dept(did)
);
INSERT INTO emp VALUE(1,'丁丁','404135199510193795',default,2);
INSERT INTO emp VALUE(2,'mary','404135199510193395',19000,1);