SET NAMES UTF8;
DROP DATABASE IF EXISTS mydata;
CREATE DATABASE mydata CHARSET=UTF8;
USE mydata
#CREATE TABLE laptop_family(
  fid INT PRIMARY KEY AUTO_INCREMENT,
  fname VARCHAR(32) NOT NULL,
  laptopCount INT DEFAULT 1 NOT NULL
);